//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association_PAT_Ukrzaliznutsa
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComentsSet
    {
        public int Id { get; set; }
        public string User { get; set; }
        public string Marshrute { get; set; }
        public string Coment { get; set; }
    }
}
