//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association_PAT_Ukrzaliznutsa
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarshrutesSet
    {
        public int Id { get; set; }
        public string NumberTrain { get; set; }
        public string PointStart { get; set; }
        public string PointEnd { get; set; }
        public string TypeTrain { get; set; }
        public string TypeLocomotive { get; set; }
        public string Locomotive { get; set; }
        public byte[] Photo { get; set; }
        public byte[] PDF { get; set; }
        public string TypeVagon { get; set; }
    }
}
