//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association_PAT_Ukrzaliznutsa
{
    using System;
    using System.Collections.Generic;
    
    public partial class NaselennuyPunktSet
    {
        public int Id { get; set; }
        public string NamePunkt { get; set; }
    }
}
