//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association_PAT_Ukrzaliznutsa
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSet
    {
        public int Id { get; set; }
        public string User { get; set; }
        public string Number { get; set; }
        public string ContragentFrom { get; set; }
        public string PointStart { get; set; }
        public string ContragentTo { get; set; }
        public string PointEnd { get; set; }
        public string TypeVagon { get; set; }
        public string PriceOfOrder { get; set; }
        public byte[] Photo { get; set; }
        public byte[] OrderPhoto { get; set; }
        public byte[] InformationOfOrder { get; set; }
        public string TypeLocomotive { get; set; }
        public string Locomotive { get; set; }
        public string Marshrute { get; set; }
        public string ProdactionInformation { get; set; }
        public string AllInformation { get; set; }
    }
}
