//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association_PAT_Ukrzaliznutsa
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketSet
    {
        public int Id { get; set; }
        public string User { get; set; }
        public string Number { get; set; }
        public string PointStart { get; set; }
        public string PointEnd { get; set; }
        public string TypeVagon { get; set; }
        public string Price { get; set; }
        public byte[] Photo { get; set; }
        public byte[] Information { get; set; }
        public string Marshrute { get; set; }
    }
}
