//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association_PAT_Ukrzaliznutsa
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainsInfoSet
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public string Locomotive { get; set; }
        public string TypeLocomotive { get; set; }
        public string TypeVagon { get; set; }
        public string Length { get; set; }
        public string LocomotivePowerEngine { get; set; }
        public byte[] Photo { get; set; }
        public byte[] PDF { get; set; }
    }
}
