//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Association_PAT_Ukrzaliznutsa
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UkrzaliznutsaDBEntities : DbContext
    {
        public UkrzaliznutsaDBEntities()
            : base("name=UkrzaliznutsaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KlientsSet> KlientsSet { get; set; }
        public virtual DbSet<LokomotiveSet> LokomotiveSet { get; set; }
        public virtual DbSet<MailSet> MailSet { get; set; }
        public virtual DbSet<MarshrutesSet> MarshrutesSet { get; set; }
        public virtual DbSet<NaselennuyPunktSet> NaselennuyPunktSet { get; set; }
        public virtual DbSet<TicketSet> TicketSet { get; set; }
        public virtual DbSet<TrainsInfoSet> TrainsInfoSet { get; set; }
        public virtual DbSet<TrainTypeSet> TrainTypeSet { get; set; }
        public virtual DbSet<TypeLocomotiveSet> TypeLocomotiveSet { get; set; }
        public virtual DbSet<UsersSet> UsersSet { get; set; }
        public virtual DbSet<VagonTypeSet> VagonTypeSet { get; set; }
        public virtual DbSet<OrderSet> OrderSet { get; set; }
        public virtual DbSet<ProdactionSet> ProdactionSet { get; set; }
        public virtual DbSet<ComentsSet> ComentsSet { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
